# Generated by Django 4.2.20 on 2025-07-11 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmes', '0004_remove_filme_diretor_filme_diretores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome da lista (ex: 'Meus Favoritos', 'Melhores de 2024')", max_length=200)),
                ('filmes', models.ManyToManyField(blank=True, to='filmes.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'listas de favoritos',
                'ordering': ['nome'],
            },
        ),
    ]
