# Generated by Django 4.2.11 on 2025-07-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('sinopse', models.TextField()),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('duracao', models.DurationField(help_text='Formato: hh:mm:ss')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
            ],
        ),
    ]
