# Generated by Django 5.2.4 on 2025-07-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diretores', '0001_initial'),
        ('filmes', '0002_filme_generos'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diretores.diretor'),
        ),
    ]
