# Generated by Django 4.2.20 on 2025-07-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diretores', '0001_initial'),
        ('filmes', '0003_filme_diretor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.AddField(
            model_name='filme',
            name='diretores',
            field=models.ManyToManyField(blank=True, to='diretores.diretor'),
        ),
    ]
